/**
 * Minigame rounds: a level activity of `count` boards (Memory Match, Number Trail, Egg Grid, Fact
 * Family Nest). Each board is a narrative minigame instance (`<round>.b<n>`) generated by
 * minigames/boards.ts and kept, with its state, in the round; `minigameMove` reduces it. A
 * finished board credits its facts, pays coins and is replaced by the next one; the last one
 * finishes the round. Moves cost no logical turn.
 */
import { ToolkitError, createMinigame, reduceMinigame } from '@aegis/narrative';
import type { MinigameDefinition, MinigameState } from '@aegis/narrative';
import type { DeepReadonly, JsonValue } from '@aegis/runtime';
import { ACTIVITY_OPTION_DEFAULTS, EVENTS } from '../contract';
import type { MinigameActivityKind, MinigameRound, RoundSource } from '../contract';
import { creditItem } from '../learning/credit';
import { roundFocus } from '../learning/selection';
import { earnCoins } from '../economy/rewards';
import { MINIGAMES, boardCredits, makeBoard } from '../minigames/boards';
import type { Options } from '../minigames/boards';
import { itemsOf } from './dragons';
import { ROUND_ALLOWANCE } from './problems';
import type { Index } from './problems';
import type { Ctx, Data, ReadState } from '../types';

export function activeMinigameRound(ctx: Ctx): MinigameRound | null {
  const round = ctx.state.round;
  return round !== null && round.type === 'minigame' && round.status === 'active' ? round : null;
}

/** The activity's options over the kind's defaults. */
export function boardOptions(data: Data, activity: MinigameActivityKind, source: RoundSource) {
  const level =
    source.kind === 'level' ? data.levels.find((l) => l.id === source.level) : undefined;
  const options = level?.activities[source.kind === 'level' ? source.activity : 0]?.options;
  return { ...ACTIVITY_OPTION_DEFAULTS[activity], ...(options ?? {}) } as Options;
}

function nextBoard(
  ctx: Ctx,
  index: Index,
  round: {
    id: string;
    activity: MinigameActivityKind;
    source: RoundSource;
    skills: string[];
    boards: number;
  },
  board: number,
  previous: DeepReadonly<MinigameDefinition> | null,
): { definition: MinigameDefinition; state: MinigameState } {
  const data = ctx.content.data;
  const pool = itemsOf(round.skills, index);
  const skills = data.skills.filter((skill) => round.skills.includes(skill.id));
  const id = `${round.id}.b${board}`;
  const definition = makeBoard({
    activity: round.activity,
    id,
    board,
    boards: round.boards,
    pool,
    focus: roundFocus(ctx.state, data, index, pool, skills),
    skills,
    options: boardOptions(data, round.activity, round.source),
    previous,
    state: ctx.state,
    random: ctx.random('problems'),
  });
  return { definition, state: createMinigame(definition, id, MINIGAMES) };
}

export function startMinigameRound(
  ctx: Ctx,
  index: Index,
  options: {
    activity: MinigameActivityKind;
    source: RoundSource;
    skills: string[];
    boards: number;
  },
): void {
  ctx.state.roundCounter += 1;
  const id = `r${ctx.state.roundCounter}`;
  ctx.enterPhase('round', ROUND_ALLOWANCE, 'cancel');
  const first = nextBoard(ctx, index, { id, ...options }, 1, null);
  ctx.state.round = {
    id,
    type: 'minigame',
    activity: options.activity,
    source: options.source,
    skills: options.skills,
    boards: options.boards,
    completed: 0,
    definition: first.definition,
    state: first.state,
    coins: 0,
    status: 'active',
    endReason: null,
  };
  ctx.emit(EVENTS.roundStarted, { round: id, activity: options.activity });
}

/** Why a minigame move is not possible now, or `null` (checked in `resolve`). */
export function moveProblem(
  state: ReadState,
  revision: number,
  move: DeepReadonly<JsonValue>,
): { code: string; message: string } | null {
  const round = state.round;
  if (round === null || round.type !== 'minigame' || round.status !== 'active') {
    return { code: 'no-board', message: 'There is no minigame board to play.' };
  }
  try {
    reduceMinigame(
      round.definition as MinigameDefinition,
      round.state as MinigameState,
      { type: 'move', revision, value: move as JsonValue },
      MINIGAMES,
    );
    return null;
  } catch (error) {
    if (!(error instanceof ToolkitError)) throw error;
    return error.code === 'AEG-NARRATIVE-STALE'
      ? { code: 'stale-move', message: 'The board changed; look again.' }
      : { code: 'invalid-move', message: 'That move is not possible on this board.' };
  }
}

/**
 * Apply a legal move: reduce the board, credit facts and coins, and move on to the next board
 * when this one is complete. Returns true when the round's last board was completed.
 */
export function applyMinigameMove(
  ctx: Ctx,
  index: Index,
  revision: number,
  move: JsonValue,
): boolean {
  const round = activeMinigameRound(ctx)!;
  const before = round.state;
  const after = reduceMinigame(
    round.definition,
    before,
    { type: 'move', revision, value: move },
    MINIGAMES,
  );
  round.state = after;
  const credit = boardCredits(
    round.definition,
    before,
    after,
    new Set(itemsOf(round.skills, index)),
  );
  for (const { item, bucket } of credit.items) creditItem(ctx, item, bucket);
  const coins = credit.coins * ctx.content.data.balance.coins.correct;
  if (coins > 0) {
    round.coins += coins;
    earnCoins(ctx, coins, 'answer');
  }
  if (after.status !== 'completed') return false;
  round.completed += 1;
  ctx.emit(EVENTS.minigameCompleted, { round: round.id, board: round.completed });
  if (round.completed >= round.boards) return true;
  const next = nextBoard(ctx, index, round, round.completed + 1, round.definition);
  round.definition = next.definition;
  round.state = next.state;
  return false;
}
