/**
 * S4's art renderers return SVG markup strings; these helpers turn them into elements.
 *
 * The markup is generated by our own deterministic renderers from IDs and numbers only (no
 * user text is ever interpolated), so it is parsed with a template element. Each instance gets
 * a fresh `idPrefix`, because two copies with the same internal IDs on one page would share
 * gradients and clip paths, and removing one would break the other.
 */
import { renderAvatar } from '../art/characters/avatars';
import { renderDragon } from '../art/dragon';
import type { DragonRenderOptions } from '../art/dragon';
import { renderIcon } from '../art/icons';
import type { KeeperAvatar } from '../../rules/contract/ids';

let serial = 0;

function nextPrefix(kind: string): string {
  serial += 1;
  return `dv-${kind}-${serial}`;
}

export function svgElement(markup: string): SVGSVGElement {
  const template = document.createElement('template');
  template.innerHTML = markup.trim();
  const node = template.content.firstElementChild;
  if (!(node instanceof SVGSVGElement)) throw new Error('Art renderer did not return an <svg>.');
  return node;
}

/** A palette icon or UI glyph from S4's icon set; decorative unless `title` is given. */
export function artIcon(
  id: string,
  options: { title?: string; className?: string; accent?: string } = {},
): SVGSVGElement {
  return svgElement(
    renderIcon(id, {
      idPrefix: nextPrefix('icon'),
      ...(options.title ? { title: options.title } : {}),
      ...(options.className ? { className: options.className } : {}),
      ...(options.accent ? { accent: options.accent } : {}),
    }),
  );
}

export function avatarArt(id: KeeperAvatar, className = 'dv-avatar'): SVGSVGElement {
  const node = svgElement(renderAvatar(id, { idPrefix: nextPrefix('avatar') }));
  node.classList.add(...className.split(' '));
  node.setAttribute('aria-hidden', 'true');
  node.setAttribute('focusable', 'false');
  node.dataset['avatar'] = id;
  return node;
}

export function dragonArt(
  options: Omit<DragonRenderOptions, 'idPrefix'>,
  className = 'dv-dragon-art',
): SVGSVGElement {
  const node = svgElement(renderDragon({ ...options, idPrefix: nextPrefix('dragon') }));
  node.classList.add(...className.split(' '));
  return node;
}
