/**
 * S4's art renderers return SVG markup strings; these helpers turn them into elements.
 *
 * The markup is generated by our own deterministic renderers from IDs and numbers only (no
 * user text is ever interpolated), so it is parsed with a template element. Each instance gets
 * a fresh `idPrefix`, because two copies with the same internal IDs on one page would share
 * gradients and clip paths, and removing one would break the other.
 */
import { renderAvatar } from '../art/characters/avatars';
import { renderBoss } from '../art/characters/bosses';
import type { BossState } from '../art/characters/bosses';
import { renderDragon, renderHatch } from '../art/dragon';
import type { DragonRenderOptions, Outfit } from '../art/dragon';
import { renderIcon } from '../art/icons';
import { renderCosmeticIcon } from '../art/cosmetics/icon';
import { renderSticker } from '../art/stickers';
import type { StickerSpec } from '../art/stickers';
import type { DragonExpression, DragonView, KeeperAvatar } from '../../rules/contract';

let serial = 0;

function nextPrefix(kind: string): string {
  serial += 1;
  return `dv-${kind}-${serial}`;
}

export function svgElement(markup: string): SVGSVGElement {
  const template = document.createElement('template');
  template.innerHTML = markup.trim();
  const node = template.content.firstElementChild;
  if (!(node instanceof SVGSVGElement)) throw new Error('Art renderer did not return an <svg>.');
  return node;
}

/** A palette icon or UI glyph from S4's icon set; decorative unless `title` is given. */
export function artIcon(
  id: string,
  options: { title?: string; className?: string; accent?: string } = {},
): SVGSVGElement {
  return svgElement(
    renderIcon(id, {
      idPrefix: nextPrefix('icon'),
      ...(options.title ? { title: options.title } : {}),
      ...(options.className ? { className: options.className } : {}),
      ...(options.accent ? { accent: options.accent } : {}),
    }),
  );
}

export function avatarArt(id: KeeperAvatar, className = 'dv-avatar'): SVGSVGElement {
  const node = svgElement(renderAvatar(id, { idPrefix: nextPrefix('avatar') }));
  node.classList.add(...className.split(' '));
  node.setAttribute('aria-hidden', 'true');
  node.setAttribute('focusable', 'false');
  node.dataset['avatar'] = id;
  return node;
}

export function dragonArt(
  options: Omit<DragonRenderOptions, 'idPrefix'>,
  className = 'dv-dragon-art',
): SVGSVGElement {
  const node = svgElement(renderDragon({ ...options, idPrefix: nextPrefix('dragon') }));
  node.classList.add(...className.split(' '));
  return node;
}

/** The art rig's outfit for a dragon's slots (empty slots left out). */
export function outfitOf(outfit: Readonly<Record<string, string | null>>): Outfit {
  const worn: Record<string, string> = {};
  for (const [slot, item] of Object.entries(outfit)) if (item !== null) worn[slot] = item;
  return worn as Outfit;
}

/** A dragon from the game view, in its stage and outfit. */
export function viewDragonArt(
  dragon: DragonView,
  options: {
    expression?: DragonExpression;
    framing?: 'stage' | 'fit';
    className?: string;
    /** Small or background dragons stay still, so a page never animates more than it needs. */
    animated?: boolean;
  } = {},
): SVGSVGElement {
  return dragonArt(
    {
      dragon: dragon.rig,
      stage: dragon.stage,
      expression: options.expression ?? dragon.expression,
      outfit: outfitOf(dragon.outfit),
      framing: options.framing ?? 'fit',
      animated: options.animated ?? true,
    },
    options.className,
  );
}

/** The hatch sequence (wobble, cracks, pop, hatchling); it plays once when inserted. */
export function hatchArt(rig: string, className = 'dv-hatch-art'): SVGSVGElement {
  const node = svgElement(renderHatch({ dragon: rig, idPrefix: nextPrefix('hatch') }));
  node.classList.add(...className.split(' '));
  return node;
}

export function bossArt(id: string, pose: BossState, className = 'dv-boss-art'): SVGSVGElement {
  const node = svgElement(renderBoss(id, pose, { idPrefix: nextPrefix('boss') }));
  node.classList.add(...className.split(' '));
  return node;
}

export function stickerArt(
  spec: Omit<StickerSpec, 'idPrefix'>,
  className = 'dv-sticker-art',
): SVGSVGElement {
  const node = svgElement(renderSticker({ ...spec, idPrefix: nextPrefix('sticker') }));
  node.classList.add(...className.split(' '));
  return node;
}

/** One cosmetic on its own (market tiles, gifts, the dressing room). */
export function cosmeticIconArt(assetId: string, className = 'dv-cosmetic-art'): SVGSVGElement {
  const node = svgElement(renderCosmeticIcon(assetId, { idPrefix: nextPrefix('cosmetic') }));
  node.classList.add(...className.split(' '));
  node.setAttribute('aria-hidden', 'true');
  return node;
}
